### ISSUE TITLE
using .neko owofy crashes discord

### ISSUE THREAD

**Issue by ExDonald** [SomeAspy/nekos-dot-life#5]
typing .neko owofy and then anything that comes after that just crashes discord. restarting keeps it crashed until its gone from the chat. would you be able to tell me why it happens / fix it? there might be more stuff that course crashes in the plugin but I didn't check

**Comment by SomeAspy** [comment]
Removed autocomplete for the command. command does not function, however it no longer crashes.

**Comment by ExDonald** [comment]
Yea i saw thanks

בתאריך יום ב׳, 19 ביולי 2021, 04:42, מאת Aiden ***@***.***>:
